// AUTO-GENERATED by illustrate-feature skill. Re-run to refresh.
import type { Feature } from "./feature-showcase";

export const features: Feature[] = [
  {
    "label": "Selected Work",
    "caption": "Scroll-driven stacked cards reveal each project on the home page.",
    "src": "/landing/case-study-01-selected-work.png",
    "alt": "Selected Work"
  },
  {
    "label": "All projects",
    "caption": "Three-up grid of every case study at /work.",
    "src": "/landing/case-study-02-all-projects.png",
    "alt": "All projects"
  },
  {
    "label": "Case study",
    "caption": "Project intro: title, role, timeline, tech stack.",
    "src": "/landing/case-study-03-case-study.png",
    "alt": "Case study"
  },
  {
    "label": "Architecture",
    "caption": "How it's built — schema, data flow, key tradeoffs.",
    "src": "/landing/case-study-04-architecture.png",
    "alt": "Architecture"
  },
  {
    "label": "What I learned",
    "caption": "Honest lessons from shipping the project.",
    "src": "/landing/case-study-05-what-i-learned.png",
    "alt": "What I learned"
  }
];
