#!/usr/bin/env tsx
/**
 * illustrate-feature — Playwright runner.
 *
 * Reads illustrate.<feature>.config.ts, captures screenshots, and writes a
 * data file the FeatureShowcase component consumes via props.
 *
 *   <FeatureShowcase features={features} />   ← user wires this once
 *
 * The component is dropped exactly once per project (the SKILL.md handles that
 * step). This script is purely about capture + data-file generation.
 *
 * Usage: tsx scripts/illustrate.ts --config illustrate.<feature>.config.ts
 */

import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { type Page, chromium } from "playwright";

interface Feature {
	label: string;
	caption: string;
	url: string;
	alt?: string;
	selector?: string;
	beforeShot?: (page: Page) => Promise<void>;
}

interface Config {
	outputDir: string; // where PNGs land (e.g. "public/landing")
	componentDir: string; // where feature-showcase.tsx + data files live
	dataSuffix?: string; // optional, names the data file: feature-showcase-<suffix>.data.ts
	features: Feature[];
	authState?: string;
	viewport?: { width: number; height: number };
	settleMs?: number;
}

const args = process.argv.slice(2);
const configIdx = args.indexOf("--config");
if (configIdx === -1 || !args[configIdx + 1]) {
	console.error("Usage: tsx scripts/illustrate.ts --config <path>");
	process.exit(1);
}
const configPath = resolve(process.cwd(), args[configIdx + 1]);

const slugify = (s: string) =>
	s
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/(^-|-$)/g, "");

async function main() {
	console.log(`Loading config: ${configPath}`);
	const mod = await import(configPath);
	const config: Config = mod.default ?? mod;

	if (!config.features?.length) {
		throw new Error("Config has no features.");
	}

	const browser = await chromium.launch();
	const context = await browser.newContext({
		viewport: config.viewport ?? { width: 1280, height: 720 },
		storageState:
			config.authState && existsSync(config.authState)
				? config.authState
				: undefined,
	});
	const page = await context.newPage();
	await mkdir(config.outputDir, { recursive: true });

	const dataSuffix = config.dataSuffix ? `-${slugify(config.dataSuffix)}` : "";
	const filePrefix = config.dataSuffix ? `${slugify(config.dataSuffix)}-` : "";

	const captured: Array<{
		label: string;
		caption: string;
		src: string;
		alt: string;
	}> = [];

	for (let i = 0; i < config.features.length; i++) {
		const f = config.features[i];
		const filename = `${filePrefix}${String(i + 1).padStart(2, "0")}-${slugify(f.label)}.png`;
		const outPath = join(config.outputDir, filename);
		console.log(
			`→ [${i + 1}/${config.features.length}] ${f.label} → ${filename}`,
		);

		await page.goto(f.url, { waitUntil: "networkidle" });
		if (f.beforeShot) await f.beforeShot(page);
		await page.waitForTimeout(config.settleMs ?? 1500);

		if (f.selector) {
			const el = await page.$(f.selector);
			if (!el)
				throw new Error(`Selector "${f.selector}" not found for "${f.label}"`);
			await el.screenshot({ path: outPath });
		} else {
			await page.screenshot({ path: outPath });
		}

		// Compute Next.js public-relative path (strip everything up to "public/").
		const publicSplit = config.outputDir.split(/public[\\/]/);
		const publicRel =
			publicSplit.length > 1 ? `/${publicSplit[1]}` : `/${config.outputDir}`;
		captured.push({
			label: f.label,
			caption: f.caption,
			src: `${publicRel}/${filename}`,
			alt: f.alt ?? f.label,
		});
	}

	await browser.close();

	const dataPath = join(
		config.componentDir,
		`feature-showcase${dataSuffix}.data.ts`,
	);
	await mkdir(dirname(dataPath), { recursive: true });
	const content = `// AUTO-GENERATED by illustrate-feature skill. Re-run to refresh.
import type { Feature } from "./feature-showcase";

export const features: Feature[] = ${JSON.stringify(captured, null, 2)};
`;
	await writeFile(dataPath, content);

	console.log("");
	console.log(`✓ ${captured.length} screenshots → ${config.outputDir}`);
	console.log(`✓ Data file → ${dataPath}`);
	console.log("");
	console.log("Render it:");
	console.log("  import { FeatureShowcase } from \"./feature-showcase\";");
	console.log(
		`  import { features } from "./feature-showcase${dataSuffix}.data";`,
	);
	console.log("  <FeatureShowcase features={features} />");
}

main().catch((err) => {
	console.error("✗ Failed:", err);
	process.exit(1);
});
